create table user_profile
(
    id           int primary key generated by default as identity,
    username     varchar(60) unique not null,
    password     varchar(64)        not null,
    nickname     varchar(60) unique not null,
    status       varchar            not null, --
    phone_number varchar(10) unique not null,
    email        varchar(50) unique not null,
    avatar_url   varchar,
    created_at   timestamp          not null
);
create table friendlist
(
    id        int primary key generated by default as identity,
    user_id   int references user_profile (id) on delete cascade,
    friend_id int references user_profile (id) on delete cascade,
    added_at  timestamp not null
);
create table private_chat
(
    id          int primary key generated by default as identity,
    first_user  int references user_profile (id),
    second_user int references user_profile (id),
    created_at timestamp
);
create table private_messages
(
    id              int primary key generated by default as identity,
    private_chat_id int references private_chat (id),
    sender_id       int references user_profile (id),
    sent_at         timestamp,
    message         text
);
create table private_files
(
    id              int primary key generated by default as identity,
    private_chat_id int references private_chat (id),
    sender_id       int references user_profile (id),
    sent_at         timestamp,
    file_url varchar,
    type varchar(10)
);
create table group_chat
(
    id          int primary key generated by default as identity,
    name        varchar(60) not null,
    description varchar,
    created_at  timestamp
);
create table group_messages
(
    id            int primary key generated by default as identity,
    group_chat_id int references group_chat (id),
    sender_id     int references user_profile (id),
    sent_at       timestamp,
    message       text
);
create table group_files
(
    id              int primary key generated by default as identity,
    group_chat_id int references group_chat (id),
    sender_id       int references user_profile (id),
    sent_at timestamp,
    file_url varchar,
    type varchar(10)
)

